// Package rig delivers a per-session CHECKOUT to an agent pod without ever
// putting a forge credential in that pod.
//
// WHY THIS EXISTS. Agent sessions are asked to read a repository -- scaffold
// most obviously, which writes .agent/ from what the project actually contains.
// The pod has no checkout (images/Dockerfile.agent creates /workspace empty and
// nothing clones into it) and, by the broker design, no forge credentials. The
// prompt used to simply claim a checkout existed, which meant the model found an
// empty directory and invented context that gonk then committed (gonk-msz).
//
// THE SHAPE. gonk-gate, at the DECISION POINT -- the moment it has read the
// project's config, compared it against the event shape and decided to act --
// registers a Grant here. The project, ref and event shape are all known at that
// instant, and the controller holds the PAT; the pod knows none of it. The pod
// later presents its session alias and receives a tarball of that tree.
//
// WHY REGISTRATION IS SEPARATE FROM DELIVERY. The registration IS the
// authorization. Without it this endpoint would be "any pod in the namespace may
// fetch any project", since the private listener has no per-caller auth. A Grant
// binds one unguessable alias to one project at one ref, so a pod can fetch
// exactly the tree its own session was granted and nothing else.
//
// Bytes are fetched lazily, on the pod's request, rather than cloned eagerly at
// registration: the decision is what has to happen at the decision point, and
// holding a clone per session on disk buys nothing but cleanup problems.
package rig

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"sync"
	"time"
)

// Grant authorizes ONE alias to fetch ONE project at ONE ref.
type Grant struct {
	// Project is the path-with-namespace, carried for logging only. Delivery
	// keys off ProjectID so a rename cannot silently redirect a fetch.
	Project   string
	ProjectID int64
	// Ref is the commit/branch the session was dispatched for. Pinning it here
	// means a later push cannot change what an in-flight session reads.
	Ref string
	// ExpiresAt bounds how long the grant is usable. A session that never starts
	// must not leave a fetchable handle on a repository indefinitely.
	ExpiresAt time.Time
}

// ErrNoGrant is returned when an alias is unknown or has expired. It is
// deliberately the SAME error for both: an unknown alias and an expired one are
// indistinguishable to a caller, so a probe cannot learn which aliases existed.
var ErrNoGrant = errors.New("rig: no grant for that alias")

// aliasPattern is what may appear in a URL path segment. Session aliases are
// generated by brokerSessionAlias (letters, digits, dots, dashes), and this is
// the guard that keeps a crafted alias from becoming a path traversal or a
// query-string smuggle when it is interpolated into a forge request.
var aliasPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$`)

// ValidAlias reports whether alias is safe to use as a path segment and map key.
func ValidAlias(alias string) bool { return aliasPattern.MatchString(alias) }

// Store holds the outstanding grants.
//
// In memory on purpose. A grant is worthless after its session ends, intake is
// the only reader, and persisting it would mean a restart could hand out a
// checkout for a session that no longer exists. The cost of the in-memory choice
// is that grants do not survive an intake restart -- see Register's note.
type Store struct {
	mu     sync.RWMutex
	grants map[string]Grant
	now    func() time.Time
}

// NewStore returns an empty Store. now may be nil (defaults to time.Now); tests
// inject a clock to exercise expiry without sleeping.
func NewStore(now func() time.Time) *Store {
	if now == nil {
		now = time.Now
	}
	return &Store{grants: make(map[string]Grant), now: now}
}

// Register records a grant.
//
// NOTE ON RESTARTS: intake has replicaCount 2 and grants are per-replica, so a
// pod may fetch from a replica that never saw the registration. The caller must
// treat a checkout miss as non-fatal and fall back to the no-checkout prompt --
// which it must do anyway, since a fetch can fail for any number of reasons.
// Making this durable would mean sharing state between replicas for something
// that is worthless minutes later.
func (s *Store) Register(alias string, g Grant) error {
	if !ValidAlias(alias) {
		return fmt.Errorf("rig: invalid alias %q", alias)
	}
	if g.ProjectID <= 0 {
		return fmt.Errorf("rig: grant for %q has no project id", alias)
	}
	if g.Ref == "" {
		return fmt.Errorf("rig: grant for %q has no ref; an unpinned checkout could change under an in-flight session", alias)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.grants[alias] = g
	s.sweepLocked()
	return nil
}

// Lookup returns the grant for alias, or ErrNoGrant.
func (s *Store) Lookup(alias string) (Grant, error) {
	s.mu.RLock()
	g, ok := s.grants[alias]
	s.mu.RUnlock()
	if !ok {
		return Grant{}, ErrNoGrant
	}
	if !g.ExpiresAt.IsZero() && s.now().After(g.ExpiresAt) {
		return Grant{}, ErrNoGrant
	}
	return g, nil
}

// Revoke drops a grant. Called when a session ends, so a pod that outlives its
// work cannot keep pulling the tree.
func (s *Store) Revoke(alias string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.grants, alias)
}

// Len reports the number of grants held, expired ones included. For metrics and
// tests; not part of the delivery path.
func (s *Store) Len() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.grants)
}

// sweepLocked drops expired grants. Called on Register so the map cannot grow
// without bound in a long-running process; there is no background goroutine to
// leak or to have to shut down.
func (s *Store) sweepLocked() {
	now := s.now()
	for alias, g := range s.grants {
		if !g.ExpiresAt.IsZero() && now.After(g.ExpiresAt) {
			delete(s.grants, alias)
		}
	}
}

// ArchiveFetcher fetches a repository tree as a gzipped tar. Satisfied by
// *glab.Client. It is the ONLY thing in this package that talks to the forge,
// and it runs in intake -- never in the agent pod.
type ArchiveFetcher interface {
	RepoArchive(ctx context.Context, projectID int64, ref string, maxBytes int64) ([]byte, error)
}
